# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('picture', models.FileField(upload_to=b'picture')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
